const baseInsertId = 20014;/*dont change this*/
const insertTexts = [  /*only add to this*/
    ["apps.action.new.call", "Anzeigen", "Afficher", "Visualizza"],
    ["apps.action.new.backtosearch", "Zurück zu den Suchresultaten", "Retour aux résultats de la recherche", "Torna ai risultati della ricerca"],
    ["apps.action.new.previousadvert", "Vorheriges Angebot", "Offre précédente", "Offerta precedente"],
    ["apps.action.new.nextadvert", "Nächstes Angebot", "Offre suivante", "Offerta successiva"],
    ["apps.dummy", "dummy", "dummy", "dummy"],
    ["apps.dummy.textwithenter", "Nächstes Angebot", "Offre suivante", "Offerta successiva"],
    ["apps.dummy.textwithenter2", "Nächstes Angebot", "Offre suivante", "Offerta successiva"],
    ["apps.dummy.textwithenter3", "Nächstes Angebot", "Offre suivante", "Offerta successiva"],
    ["apps.action.nav.search", "Suchen", "Rechercher", "Cercare"],
    ["apps.action.nav.login", "Anmelden", "Se connecter", "Accedere"],
    ["apps.action.nav.account", "Benutzerkonto", "Compte d’utilisateur", "Account utente"],
    ["apps.action.nav.favorites", "Favoriten", "Favoris", "Preferiti"],
    ["apps.action.nav.listings", "Inserate", "Annonces", "Annunci"],
    ["apps.action.nav.insert", "Inserat erstellen", "Créer une annonce", "Creare un annuncio"],
    ["apps.action.next", "Vorwärts", "Suivant", "Avanti"],
    ["apps.action.approve", "Genehmigen", "Approuver", "Approvare"],
    ["apps.action.reject", "Ablehnen", "Rejeter", "Rifiutare"],
    ["apps.rejected", "Abgelehnt", "Rejeté", "Respinto"],
    ["apps.deleted", "Gelöscht", "Supprimé", "Eliminato"],
    ["apps.confirmation.promoteadvert", "Sind Sie sicher, Aktionen mit Paypal zu kaufen?", "Êtes-vous sûr d'acheter des promotions avec paypal?", "Sei sicuro di acquistare promozioni con paypal?"],
    ["apps.message.promotesuccess", "Galerie angehoben!", "Galerie boostée!", "Galleria potenziata!"],
    ["apps.confirmation.deleteadvert", "Sind Sie sicher, diese Anzeige zu löschen?", "Êtes-vous sûr de vouloir supprimer cette annonce?", "Sei sicuro di eliminare questo annuncio?"],
    ["apps.confirmation.activate", "Sind Sie sicher, diese Anzeige zu aktivieren?", "Êtes-vous sûr d'activer cette annonce?", "Sei sicuro di attivare questo annuncio?"],
    ["apps.confirmation.deactivate", "Sind Sie sicher, diese Anzeige zu deaktivieren?", "Êtes-vous sûr de désactiver cette publicité?", "Sei sicuro di disattivare questo annuncio?"],
    ["apps.allfilter", "Alle Filter", "Tous les filtres", "Tutti i filtri"],
    ["apps.action.openmap", "In Google Maps öffnen", "Ouvrir dans Google Maps", "Apri in Google Maps"],
    ["apps.insertion.step.categoryattribute", "Kategorie & Attribute", "Catégorie et attributs", "Categoria e attributi"],
    ["apps.insertion.step.photo", "Fotos", "Photos", "Fotografie"],
    ["apps.insertion.step.titledescription", "Titel Beschreibung", "Description du titre", "Descrizione del titolo"],
    ["apps.insertion.step.contact", "Kontakt", "Contact", "Contatto"],
    ["apps.insertion.step.previewpublish", "Vorschau & Veröffentlichung", "Prévisualiser et publier", "Anteprima e pubblicazione"],
    ["apps.insertion.title.categoryattribute", "Bitte wählen Sie die Kategorie und Attribute Ihrer Anzeige aus", "Veuillez sélectionner la catégorie et les attributs de votre annonce", "Seleziona la categoria e gli attributi del tuo annuncio"],
    ["apps.insertion.title.photo", "Bitte wählen Sie Ihre Werbefotos aus", "Veuillez sélectionner les photos de votre annonce", "Seleziona le foto dell'annuncio"],
    ["apps.insertion.title.titledescription", "Bitte geben Sie Ihren Anzeigentitel und Ihre Beschreibung an", "Veuillez remplir le titre et la description de votre annonce", "Si prega di compilare il titolo e la descrizione dell'annuncio"],
    ["apps.insertion.title.contact", "Bitte geben Sie Ihre Kontaktinformationen ein", "Veuillez remplir vos coordonnées", "Si prega di compilare le informazioni di contatto"],
    ["apps.insertion.title.previewpost", "Bitte überprüfen Sie Ihre Anzeige, bevor Sie sie veröffentlichen", "Veuillez examiner votre annonce avant de la publier", "Si prega di rivedere il proprio annuncio prima di pubblicarlo"],
    ["apps.totalphoto", "Gesamt", "Total", "Totale"],
    ["apps.addphotohint", "Ziehen Sie eine oder mehrere Dateien hierher", "Faites glisser un ou plusieurs fichiers ici", "Trascina uno o più file qui"],
    ["apps.uploading", "Hochladen", "Téléchargement", "Caricamento in corso"],
    ["apps.photo", "Foto", "Photo", "Foto"],
    ["apps.homepage", "Startseite", "Page d’accueil", "Pagina iniziale"],
    ["apps.validationtitle", "Bitte füllen Sie diese fehlenden Informationen aus", "Veuillez remplir ces informations manquantes", "Si prega di compilare queste informazioni mancanti"],
    //["", "", "", ""],
    //["", "", "", ""],
    //["", "", "", ""],
];
module.exports = {
    baseInsertId: baseInsertId,
    insertTexts: insertTexts,
    EN_TEXT_PACKAGEDEL: {
        ROOT: [
            { key: "apps.action.nav.search", text: "Search" },
            { key: "apps.action.nav.login", text: "Login" },
            { key: "apps.action.nav.account", text: "Account" },
            { key: "apps.action.nav.favorites", text: "Favorites" },
            { key: "apps.action.nav.listings", text: "Listings" },
            { key: "apps.action.nav.insert", text: "Insert new advert" },
            { key: "apps.action.new.backtosearch", text: "Back to search" },
            { key: "apps.action.new.previousadvert", text: "Previous advert" },
            { key: "apps.action.new.nextadvert", text: "Next advert" },
            { key: "apps.category", text: "Category" },
            { key: "apps.categories", text: "Categories" },
            { key: "apps.subcategory", text: "Sub-category" },
            { key: "apps.subcategories", text: "Sub-categories" },
            { key: "apps.inallcategories", text: "All categories" },
            { key: "apps.filter", text: "Filter" },
            { key: "apps.location", text: "Location" },
            { key: "apps.all", text: "All" },
            { key: "apps.radius", text: "Radius" },
            { key: "apps.state", text: "State" },
            { key: "apps.action.back", text: "Back" },
            { key: "apps.action.next", text: "Next" },
            { key: "apps.action.close", text: "close" },
            { key: "apps.action.apply", text: "Apply" },
            { key: "apps.action.cancel", text: "Cancel" },
            { key: "apps.action.search", text: "Search" },
        ],
        HOME: [
            { key: 'apps.action.search', text: 'Search' },
            { key: 'apps.searchkeyword', text: 'Looking on anibis' },
            { key: 'apps.conditions', text: 'Terms and conditions of use' },
            { key: 'apps.search', text: 'search' },
            { key: 'apps.safety', text: 'safety instructions' },
            { key: 'apps.tariff', text: 'Prices' },
            { key: 'apps.insertion', text: 'Advertise' },
            { key: 'apps.myanibis', text: 'My anibis' },
            { key: 'apps.home.lastsearch.label', text: 'Last search' },
            { key: 'apps.home.lastviewed.label', text: 'Last viewed' },
            { key: 'apps.home.favorites.label', text: 'Your favorites' },
            { key: 'apps.home.new.cars', text: 'Used & new cars' },
            { key: 'apps.home.new.inallcategories', text: 'All Categories' },
            { key: 'apps.home.new.jobs', text: 'Job offers' },
            { key: 'apps.home.new.realestate.buy', text: 'Buy real estate' },
            { key: 'apps.home.new.realestate.rent', text: 'Rent a property' },
            { key: 'apps.home.gallery.label', text: 'Gallery' },
            { key: 'apps.action.home.more.favorites', text: 'All' },
            { key: 'apps.action.home.more.lastsearch', text: 'More' },
            { key: 'apps.action.home.more.lastviewed', text: 'More' },
            { key: 'apps.home.new.title', text: 'Free Classifieds - Search% d for listings' },
            { key: 'apps.home.new.newoffers', text: 'The latest offers' }
        ],
        SEARCH: [
            { key: "apps.category", text: "category" },
            { key: "apps.categories", text: "categories" },
            { key: "apps.subcategory", text: "subcategory" },
            { key: "apps.subcategories", text: "subcategories" },
            { key: "apps.inallcategories", text: "inallcategories" },
            { key: "apps.filter", text: "Filter" },
            { key: "apps.action.resetfilters", text: "Reset filters" },
            { key: "apps.location", text: "location" },
            { key: "apps.all", text: "all" },
            { key: "apps.radius", text: "radius" },
            { key: "apps.state", text: "state" },
            { key: "apps.from", text: "from" },
            { key: "apps.to", text: "to" },
        ],
        // DETAIL_BROWSER: [   /*DETAIL_BROWSER*/
        //     { key: "apps.action.new.backtosearch", text: "Back to search" },
        //     { key: "apps.action.new.previousadvert", text: "Previous advert" },
        //     { key: "apps.action.new.nextadvert", text: "Next advert" },
        // ],
        DETAIL: [
            { key: 'apps.share', text: 'Share' },
            { key: 'apps.action.showmorelistings', text: 'More offers from this provider' },
            { key: 'apps.action.contactemail', text: 'Write a message' },
            { key: 'apps.advertid', text: 'Advertisement number' },
            { key: 'apps.listings', text: 'Ads' },
            { key: 'apps.seller', text: 'Providers' },
            { key: 'apps.registeredsince', text: 'Registered since' },
            { key: 'apps.action.contactseller', text: 'Contact the Provider' },
            { key: 'apps.morelistings', text: 'More offers from this provider' },
            { key: 'apps.safety', text: 'Safety instructions' },
            { key: 'apps.action.reportfraud', text: 'Report suspicious listing' },
            { key: 'apps.description', text: 'Description' },
            { key: 'apps.insertion.contact', text: 'Location' },
            { key: 'apps.listing', text: 'Listing' },
            { key: 'apps.action.home.more', text: 'Show all' },
            { key: 'apps.action.copylink', text: 'Copy link' },
            { key: 'apps.details', text: 'Details' },
            { key: 'apps.action.print', text: 'Print' },
            { key: 'apps.action.favorite', text: 'Favourite' },
            { key: 'apps.advertedit', text: 'Last change' },
            { key: 'apps.action.new.call', text: 'Call' }
        ],
        LOGIN_REGISTER: [
            { key: "apps.password", text: "password" },
            { key: "apps.username", text: "username" },
            { key: "apps.email", text: "email" },
            { key: "apps.action.retrievepassword", text: "Retrieve password" },
            { key: "apps.action.login", text: "login" },
            { key: "apps.message.noaccount", text: "noaccount" },
            { key: "apps.action.createaccount", text: "createaccount" },
            { key: "apps.login", text: "login" },
            { key: "apps.needlogin", text: "needlogin" },
            { key: "apps.message.loginfail", text: "loginfail" },
            { key: "apps.message.loginsuccess", text: "loginsuccess" },
            { key: "apps.action.login", text: "login" },
            { key: "apps.action.backtosearch", text: "backtosearch" },
            { key: "apps.action.cancel", text: "cancel" },
            { key: "apps.action.continue", text: "continue" },
            { key: "apps.settings", text: "settings" },
            { key: "apps.action.back", text: "back" },
            { key: "apps.footer.responsibility", text: "responsibility" },
            { key: "apps.footer.copyright", text: "copyright" },
            { key: "apps.new.checkmandatoryfield", text: "checkmandatoryfield" },
            { key: "apps.action.revealpassword", text: "revealpassword" },
            'apps.action.change',
            'apps.action.hidepassword',
        ],
        FAVORITE: [
            { key: "apps.favorites", text: "favorites" },
            { key: "apps.nofavorites", text: "nofavorites" },
            { key: "apps.nofavorites.description", text: "nofavorites" },
            { key: "apps.deletedfavorite", text: "deletedfavorite" },
        ],
        HISTORY: [
            { key: "apps.nohistory", text: "nohistory" },
            { key: "apps.history", text: "history" },
            { key: "apps.nohistory.description", text: "nohistory" },
        ],
        INSERT: [
            { key: "apps.action.addimage", text: "addimage" },
            { key: "apps.hinttitle", text: "hinttitle" },
            { key: "apps.hintdescription", text: "hintdescription" },
            { key: "apps.categories", text: "categories" },
            { key: "apps.pricetype", text: "pricetype" },
            { key: "apps.action.no", text: "no" },
            { key: "apps.action.yes", text: "yes" },
            { key: "apps.insertion.contact.location", text: "insertion.contact.location" },
            { key: "apps.contacttype", text: "contacttype" },
            { key: "apps.contacttypeform", text: "contacttypeform" },
            { key: "apps.contacttypephone", text: "contacttypephone" },
            { key: "apps.contacttypeboth", text: "contacttypeboth" },
            { key: "apps.contacttype.message", text: "contacttype.message" },
            { key: "apps.links.conditions.anchor.new", text: "links.conditions.anchor.new" },
            { key: "apps.links.conditions.and", text: "links.conditions.and" },
            { key: "apps.links.rules.anchor", text: "links.rules.anchor" },
            { key: "apps.action.publish", text: "publish" },
            { key: "apps.insertion.category.select", text: "insertion.category.select" },
            { key: "apps.advertcountry", text: "advertcountry" },
            { key: "apps.advertzipcode", text: "advertzipcode" },
            { key: "apps.advertstreet", text: "advertstreet" },
            { key: "apps.general.inputoptional", text: "general.inputoptional" },
            { key: "apps.action.editpicture", text: "editpicture" },
            { key: "apps.action.editpicture", text: "editpicture" },
        ],
        ACCOUNT: [
            { key: "apps.listings.description", text: "listings" },
            { key: "apps.createlistings", text: "createlistings" },
            { key: "apps.createlistings.description", text: "createlistings" },
            { key: "apps.accountsettings", text: "accountsettings" },
            { key: "apps.accountsettings.description", text: "accountsettings" },
            { key: "apps.createlistings", text: "createlistings" },
            { key: "apps.createlistings.description", text: "createlistings" },
            { key: "apps.accountsettings", text: "accountsettings" },
            { key: "apps.accountsettings.description", text: "accountsettings" },
            { key: "apps.account.signedinas", text: "signedinas" },
            { key: "apps.account.usersettings", text: "usersettings" },
            { key: "apps.action.changepassword", text: "changepassword" },
            { key: "apps.action.logout", text: "logout" },
            { key: "apps.action.backtosearch", text: "backtosearch" },
            { key: "apps.action.cancel", text: "cancel" },
            { key: "apps.footer.responsibility", text: "responsibility" },
            { key: "apps.footer.copyright", text: "copyright" },
            { key: "apps.email", text: "email" },
            { key: "apps.registeredsince", text: "registeredsince" },
            { key: "apps.action.back", text: "back" },
        ],
        MY_ADVERTS: [
            { key: "apps.statsviews", text: "Views" },
            { key: "apps.statsrequests", text: "Requests" },
            { key: "apps.onlineto", text: "Online to" },
            { key: "apps.datedeactivate", text: "Date deactivated" },
            { key: "apps.datecreate", text: "Date created" },
            { key: "apps.dateexpired", text: "Date expired" },
            { key: "apps.active", text: "Active" },
            { key: "apps.inactive", text: "Inactive" },
            { key: "apps.draft", text: "Draft" },
            { key: "apps.expired", text: "Expired" },
            { key: "apps.inpreview", text: "Pending" },
            { key: "apps.deleted", text: "Deleted" },
            { key: "apps.rejected", text: "Rejected" },
            { key: "apps.promotion", text: "Promotion" },
            { key: "apps.action.upgradead", text: "Upgrade" },
            { key: "apps.statisticstatus", text: "Statistic" },
            { key: "apps.statisticreset", text: "Rreset" },
            { key: "apps.action.edit", text: "Edit" },
            { key: "apps.action.complete", text: "Complete" },
            { key: "apps.action.activate", text: "Activate" },
            { key: "apps.action.pause", text: "Pause" },
            { key: "apps.action.deletelisting", text: "Delete" },
            { key: "apps.listings.topposition", text: "Top position" },
            { key: "apps.listings.highlight", text: "Highlight" },
            { key: "apps.listings.websitelink", text: "Website link" },
            { key: "apps.listings.homepagegallery", text: "Homepage gallery" },
            { key: "apps.listings.turbo", text: "Turbo" },
            { key: "apps.listings.megadeal", text: "Megadeal" },
            { key: "apps.action.deeplink.mylistings.ios", text: "My adverts" },
            { key: "apps.action.approve", text: "Approve" },
            { key: "apps.action.reject", text: "Reject" },
            { key: "apps.confirmation.promoteadvert", text: "Purchase promotions with paypal" },
            { key: "apps.message.promotesuccess", text: "Gallery boosted!" },
            { key: "apps.confirmation.deleteadvert", text: "Are you sure to delete this advert?" },
            { key: "apps.confirmation.activate", text: "Are you sure to activate this advert?" },
            { key: "apps.confirmation.deactivate", text: "Are you sure to deactivate this advert?" },
        ]
    }
};